gamer:
  id: 1001
  servlet-boot: netty
  conf:
    servlet:
      servletName: DispatcherServlet                                   # Servlet名称
      servletClass: com.thinkerwolf.gamer.core.mvc.DispatcherServlet   # Servlet类名
      initParams:                                                      # 参数列表
        componentScanPackage: com.thinkerwolf                          # 组件扫描包名
        compress: true                                                 # 传输压缩(仅http生效)
        #    sessionManager: com.thinkerwolf.gamer.core.servlet.RedisSessionManager
        #    sessionRedisHost: localhost
        #    sessionRedisPort: 6379
        sessionTimeout: 120                                            # Session超时时间(s)
        sessionTickTime: 5                                             # Session检查tick(s)
        resourceLocation: META-INF/resources                           # 静态资源位置
        filters: com.thinkerwolf.gamer.test.filter.ExceptionFilter     # Filter列表，以;为间隔

    # 监听器配置列表
    listeners:
      - com.thinkerwolf.gamer.test.listener.LocalSessionListener
      - com.thinkerwolf.gamer.test.listener.LocalSessionAttributeListener
      - com.thinkerwolf.gamer.rpc.mvc.RpcServiceLoadListener
      - com.thinkerwolf.gamer.swagger.SwaggerEnableListener

    # Net配置列表
    net:
      - workerThreads: 5     # worker线程数
        coreThreads: 10      # Servlet业务核心线程
        maxThreads: 11       # Servlet业务最大线程
        countPerChannel: 100 # 每个Channel最大并发数量
        protocol: tcp        # 协议
        port: 9090           # 端口
        options:             # Options
          so_keepalive: true
        childOptions:        # ChildOptions
          tcp_nodelay: true
      - workerThreads: 5
        coreThreads: 10
        maxThreads: 11
        countPerChannel: 100 # 客户端最大并发数量
        protocol: http
        ssl:                 # ssl配置
          enabled: false
          keystoreFile: C:/Users/wukai/keystore.jks
          keystorePass: Wk1234lc
        port: 8090
        options:
          so_keepalive: true
        childOptions:
          tcp_nodelay: true